version: '3'

services:
  proxy_nginx: 
    build: ./nginx
    container_name: proxy_nginx
    image: nginx:latest
    # volumes:
    #   - ./nginx/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    #   - ./nginx/nginx/log:/var/log/nginx/
    # - ./nginx/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      # - 443:443
    depends_on: 
      - react

  react:
    build: ./react-image-compressor
    container_name: react
    ports:
      - 5000:5000
    
