apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: proxy-nginx
  name: proxy-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: proxy-nginx
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose.exe convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: proxy-nginx
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Never
        name: proxy-nginx
        ports:
        - containerPort: 80
        # volumeMounts:
        # - mountPath: /var/log/nginx
        #   name: volume
        resources: {}
      serviceAccountName: ""

      volumes: null
      # - name: volume
      #   hostPath:
      #       path: /mount/
status: {}
