FROM node
RUN yarn global add serve
# WORKDIR .
COPY package.json ./
RUN yarn
COPY . ./
RUN yarn build
CMD serve -s build


# # Stage 1 - the build process
# FROM node:7.10 as build-deps
# RUN yarn global add serve
# WORKDIR .
# COPY package.json ./
# RUN yarn
# COPY . ./
# RUN yarn build
# CMD serve -s build

# # Stage 2 - the production environment
# FROM nginx:1.12-alpine
# COPY --from=build-deps /usr/src/app/build /usr/share/nginx/html
# EXPOSE 80
# CMD ["nginx", "-g", "daemon off;"]