version: '3'

services:
  nginx: 
    image: nginx:latest
    container_name: nginx
    # volumes:
    #   - ./nginx/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    #   - ./nginx/nginx/log:/var/log/nginx/
    ports:
      - 80:80
      # - 443:443
    depends_on: 
      - react

  react:
    build: ./react
    container_name: react