FROM nginx:alpine

#!/bin/sh

COPY ./nginx/nginx.conf /etc/nginx/conf.d/default.conf


## Remove default nginx index page
RUN rm -rf /usr/share/nginx/html/*

# Copy from the stahg 1
# COPY --from=builder /react-ui/build /usr/share/nginx/html

EXPOSE 80

ENTRYPOINT ["nginx", "-g", "daemon off;"]